# Color scale settings (for input values that are Z-score normalized)
color_scale:
  min_value: -2.0  # Minimum value for the color scale
  max_value: 2.0   # Maximum value for the color scale
  gradient:        # Colors for the color scale
    - color: blue  # Corresponds to negative values
    - color: white # Corresponds to mid values
    - color: red   # Corresponds to positive values

# Color scale settings (for raw expression values such as TPM)
#color_scale:
#  min_value: 0       # Minimum value for the color scale
#  max_value: 2.0     # Maximum value for the color scale
#  gradient:  viridis # Colors for the color scale